export enum SettingTimeChart {
    SECOND = "second",
    MINUTE = "minute",
    MINUTES = "minutes",
    HOUR = "hour",
    HOURS = "hours",
    DAY = "day",
    DAYS = "days",
    WEEK = "week",
    WEEKS = "weeks",
    MONTH = "month",
    MONTHS = "months",
    YEAR = "year",
    YEARS = "years",
    ONE_MINUTE = `${1} ${MINUTE}`,
    TEN_MINUTES = `${10} ${MINUTES}`,
    THIRTY_MINUTES = `${30} ${MINUTES}`,
    ONE_HOUR = `${1} ${HOUR}`,
    ONE_DAY = `${1} ${DAY}`,
    ONE_WEEK = `${1} ${WEEK}`,
    ONE_MONTH = `${1} ${MONTH}`,
    ONE_YEAR = `${1} ${YEAR}`,
}